spring:
  profiles:
    active:
    - production
  application:
    name: RoutineHelper-Desktop
  jackson:
    serialization:
      write-dates-as-timestamps: false
sound:
  announce:
    seconds:
      beforeDue: 300
      afterDue: 3600